first:
  completes:
    - affectionate
    - benedryl
    - benefit
    - benefits
    - "Bendy - Straw"
    - "burnt sienna"
    - contradict
    - derelict
    - etiquette
    - feminist
    - "Fiddy - Cent"
    - impressionist
    - medalist
    - megabit
    - methodist
    - perfectionist
    - projectionist
    - protectionist
    - receptionist
    - secessionist
    - specialist
    - supremacist 
  splits:
    front:
      - antenna
      - bean
      - bendy
      - fiddy
      - henna
      - queeny
      - teeny
      - weenie
    back:
      - addict
      - bricked
      - clicked
      - dangle
      - dank
      - flicked
      - kicked
      - licked
      - nicked
      - picked
      - pricked
      - sicked
      - slicked
      - strict
      - ticked
      - tricked 
last:
  completes:
    - cumberbund
    - cumbersome
    - "Vegetable - Patch"
    - "Spinach - Patch"
    - "Lumbar - Support"
    - "Lumber - Yard"
  splits:
    front:
      - amber
      - "and/or"
      - asunder
      - blunder
      - bomber
      - buffer
      - bumbler
      - bumper
      - bunker
      - concert
      - crinkle
      - cucumber
      - cumbent
      - cumbered
      - cumbers
      - cummer
      - dumber
      - dumper
      - dunbar
      - dunker
      - encumber
      - encumbered
      - gunner
      - hummer
      - hunger
      - hunker
      - hunter
      - lumbar
      - lumber
      - lumper
      - jumper
      - junker
      - monger
      - mother
      - number
      - numbers
      - other
      - plunder
      - punter
      - rubber
      - slumber
      - somber
      - spelunker 
      - stumper
      - summer
      - sunder
      - thumper
      - thunder
      - tumbler
      - unbar
      - under
      - wonder
      - younger
      - younker 
    back:
      - act
      - back
      - badge
      - birch
      - catch
      - gash
      - gnash
      - hatch
      - latch
      - madge
      - match
      - natch
      - pack
      - pact
      - patch
      - pants
      - plotz
      - ranch
      - rekt
      - scratch
      - smash
      - snatch
      - stash
      - "'stache"
      - thatch
      - trash
      - wrap
      - wretch
